version: '3.8'

services:
  # Override backend for development with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - uploads_data:/app/uploads
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres_password@postgres:5432/video_funnel_builder?schema=public
      JWT_SECRET: dev-jwt-secret-key
      JWT_REFRESH_SECRET: dev-refresh-secret-key
      FRONTEND_URL: http://localhost:5173
      MAX_FILE_SIZE: 10485760
      UPLOAD_DIR: /app/uploads
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
    command: >
      sh -c "
        echo 'Starting development server...' &&
        echo 'Waiting for database connection...' &&
        npx prisma db push &&
        npx prisma generate &&
        echo 'Database ready! Starting backend...' &&
        npm run dev
      "
